In [6]:
import anndata as an
import scanpy as sc
import pandas as pd
import numpy as np
import os
from scipy.sparse import csr_matrix
from scipy.sparse import issparse
import gget
import pyranges as pr

import seaborn as sns
import matplotlib.pyplot as plt

sc.settings.verbosity = 3

In [7]:
fpath = "/scratch/indikar_root/indikar1/shared_data/epi2me_pipeline_run/outputs/full_reads_run_mar_19/32f7539deda847c0a5dc4405f98ebd86/32f7539deda847c0a5dc4405f98ebd86.transcriptome.gff.gz"

gdf = pr.read_gff(fpath)
gdf.head()

+--------------+------------+--------------+-----------+-----------+-------+
|   Chromosome | Source     | Feature      |     Start |       End | +15   |
|   (category) | (object)   | (category)   |   (int64) |   (int64) | ...   |
|--------------+------------+--------------+-----------+-----------+-------|
|            1 | StringTie  | transcript   |     16958 |     17607 | ...   |
|            1 | StringTie  | exon         |     16958 |     17053 | ...   |
|            1 | StringTie  | exon         |     17230 |     17607 | ...   |
|            1 | StringTie  | transcript   |     34893 |     35511 | ...   |
|            1 | StringTie  | exon         |     34893 |     35511 | ...   |
|            1 | StringTie  | transcript   |     39610 |     39935 | ...   |
|            1 | StringTie  | exon         |     39610 |     39935 | ...   |
|            1 | StringTie  | transcript   |    134774 |    136110 | ...   |
+--------------+------------+--------------+-----------+-----------+-------+
Stranded PyRanges object has 8 rows and 20 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
15 hidden columns: Score, Strand, Frame, transcript_id, gene_id, xloc, class_code, ... (+ 8 more.)

In [12]:
df = gdf.df
df = df[df['Feature'] == 'transcript']
df = df[df['gene_name'].notna()]
print(f"{df.shape=}")
df.head()

df.shape=(250320, 20)

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,transcript_id,gene_id,xloc,class_code,tss_id,exon_number,cmp_ref,cmp_ref_gene,contained_in,gene_name,ref_gene_id,ref_gene_name
0,1,StringTie,transcript,16958,17607,.,+,.,1.stringtie.79.1,1.stringtie.79,XLOC_000001,s,TSS1,NaN,ENST00000488147,WASH7P,NaN,NaN,NaN,NaN
3,1,StringTie,transcript,34893,35511,.,+,.,1.stringtie.81.1,1.stringtie.81,XLOC_000002,x,TSS2,NaN,ENST00000417324,FAM138A,NaN,NaN,NaN,NaN
5,1,StringTie,transcript,39610,39935,.,+,.,1.stringtie.82.1,1.stringtie.82,XLOC_000003,u,TSS3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,StringTie,transcript,134774,136110,.,+,.,1.stringtie.95.1,1.stringtie.95,XLOC_000004,o,TSS4,NaN,ENST00000442987,NaN,NaN,CICP27,ENSG00000233750,CICP27
9,1,StringTie,transcript,137906,140458,.,+,.,1.stringtie.97.1,1.stringtie.97,XLOC_000005,s,TSS5,NaN,ENST00000493797,ENSG00000239906,NaN,NaN,NaN,NaN

In [10]:
df = df[df['Feature'] == 'transcript']